- title: HRM
  type: group
  icon: teamoutlined
  children:
    - title: Dashboard
      icon: dashboardoutlined
    - title: Departments
      icon: apartmentoutlined
    - title: Employees
      icon: useroutlined
    - title: Leave Requests
      icon: calendaroutlined
