blocks:
  - key: filterForm
    type: filterForm
    coll: nb_pm_tasks
    fields:
      - field: name
        label: Search
        filterPaths:
          - name
          - description
      - status
      - priority
    js_items:
      - key: tasks_status_buttons
        file: ./js/tasks_filterForm_status_buttons.js
        desc: Task Status Filter Buttons
    field_layout:
      - - '[JS:Task Status Filter Buttons]'
      - - name
        - status
        - priority
  - key: table
    type: table
    coll: nb_pm_tasks
    fields:
      - field: name
        popup: true
      - status
      - priority
      - due_date
      - field: project
        popup: true
      - field: assignee
        popup: true
      - createdAt
    actions:
      - filter
      - refresh
      - addNew
    recordActions:
      - edit
      - delete
layout:
  - - filterForm
  - - table
