blocks:
  - key: filterForm
    type: filterForm
    coll: nb_pm_tasks
    fields:
      - field: name
        label: Search
        filterPaths:
          - name
          - description
      - project
      - assignee
    js_items:
      - key: task_status_filters
        file: ./js/task_status_filters.js
        desc: Task Status Filters
    field_layout:
      - - '[JS:Task Status Filters]'
      - - name
        - project
        - assignee
  - key: table
    type: table
    coll: nb_pm_tasks
    filter:
      status.$eq: '{{ ctx.urlSearchParams.status }}'
    fields:
      - field: name
        clickToOpen: true
      - project
      - assignee
      - status
      - priority
      - due_date
      - estimated_hours
      - createdAt
    actions:
      - filter
      - refresh
      - addNew
    recordActions:
      - edit
      - delete
layout:
  - - filterForm
  - - table
