blocks:
  - key: filterForm
    type: filterForm
    coll: nb_pm_tasks
    fields:
      - field: name
        label: Search
        filterPaths:
          - name
          - description
      - status
      - priority
    js_items:
      - key: filter_buttons
        file: ./js/filter_buttons.js
        desc: Status Filter Buttons
    field_layout:
      - - '[JS:Status Filter Buttons]'
      - - name
        - status
        - priority
  - key: table
    type: table
    coll: nb_pm_tasks
    fields:
      - field: name
        popup: true
      - project
      - assignee
      - status
      - priority
      - due_date
      - estimated_hours
      - createdAt
    actions:
      - filter
      - refresh
      - addNew
    recordActions:
      - edit
      - delete
layout:
  - - filterForm
  - - table
