blocks:
  - key: filterForm
    type: filterForm
    coll: nb_erp_inventory
    fields:
      - field: product
        label: Product
        filterPaths:
          - product.id
      - field: warehouse
        label: Warehouse
        filterPaths:
          - warehouse.id
    field_layout:
      - - product
        - warehouse
  - key: table
    type: table
    coll: nb_erp_inventory
    fields:
      - field: product
        clickToOpen: true
      - field: warehouse
        clickToOpen: true
      - quantity
      - last_updated
    recordActions:
      - type: edit
        stepParams:
          buttonSettings:
            general:
              title: Edit
              icon: null
              type: link
          popupSettings:
            openView:
              mode: drawer
              size: large
              pageModelClass: ChildPageModel
              dataSourceKey: main
              collectionName: ''
              uid: 2dtgei7ygy1
          displayFieldSettings:
            clickToOpen:
              clickToOpen: true
        props:
          title: Edit
          icon: null
          type: link
        key: edit_edit
    actions:
      - filter
      - refresh
      - addNew
layout:
  - - filterForm
  - - table
