group_id: 358340356210689
pages:
  dashboard:
    route_id: 358340356210690
    page_uid: c6innygetxj
    tab_uid: 2acw527wzrt
    grid_uid: 13wst2v34b5
    blocks:
      kpi_1:
        uid: 8yclbmn5mv9
        type: jsBlock
        grid_uid: ''
        fields: {}
      kpi_2:
        uid: mw4pltxgpk0
        type: jsBlock
        grid_uid: ''
        fields: {}
      kpi_3:
        uid: ya6mqnlb65d
        type: jsBlock
        grid_uid: ''
        fields: {}
      kpi_4:
        uid: 89kuf1uja4e
        type: jsBlock
        grid_uid: ''
        fields: {}
      chart_1:
        uid: rtu38nmvqqw
        type: chart
        grid_uid: ''
        fields: {}
      chart_2:
        uid: p4duju3khi6
        type: chart
        grid_uid: ''
        fields: {}
      chart_3:
        uid: xjqm3p6m40n
        type: chart
        grid_uid: ''
        fields: {}
      chart_4:
        uid: j26c2bstr4m
        type: chart
        grid_uid: ''
        fields: {}
      chart_5:
        uid: 4yy1lz6xrwu
        type: chart
        grid_uid: ''
        fields: {}
  products:
    route_id: 358340358307840
    page_uid: b3z1535j2au
    tab_uid: n0prkuziod4
    grid_uid: 1cfx62uguu2
    blocks:
      filterForm:
        uid: 0fh3jwc5q29
        type: filterForm
        grid_uid: llcvy26nmii
        fields:
          category:
            wrapper: n3gqcrlfuyi
            field: uqdc734b6kg
          supplier:
            wrapper: 5u3iyvy8s48
            field: 2gnjbpoa912
          name:
            wrapper: 4elf0ae03oc
            field: 25kzi4cn5k7
      table:
        uid: 2i070x8wcoi
        type: table
        grid_uid: ''
        fields:
          sku:
            wrapper: vlb55ort6c6
            field: gjgjnzooaiu
          supplier:
            wrapper: km9mrm0siay
            field: 601p31qyuin
          unitPrice:
            wrapper: pfq2cze9uw0
            field: 4koyg9oaoen
          name:
            wrapper: w8kf7bu5v95
            field: vcaj9xc1rgj
          reorderLevel:
            wrapper: kx78mi2180t
            field: ox8y42ceac8
          category:
            wrapper: vq45bn3l5rm
            field: nnaq4jr5ttn
          stockQuantity:
            wrapper: niema2vb3rq
            field: 7enx277amnx
        actions:
          filter:
            uid: rr5pnm711ld
          refresh:
            uid: ijalauquy0l
          addNew:
            uid: zcdglhkh5kn
          export:
            uid: zazkoli85sj
        record_actions:
          edit:
            uid: qw0u9uhqs5m
          delete:
            uid: o1jd3wok9kw
  suppliers:
    route_id: 358340360404992
    page_uid: uulb8dp70lh
    tab_uid: ru1x73ughy3
    grid_uid: 49kotusxu7z
    blocks:
      filterForm:
        uid: 4h4fg6sen0c
        type: filterForm
        grid_uid: v2wsnnaq9yy
        fields:
          rating:
            wrapper: apvbrl1jt9a
            field: kwxs22944kf
          status:
            wrapper: lo9bmnaofxd
            field: u29mq1fcojx
          name:
            wrapper: qpr17c9ocrf
            field: 7taeqzha31v
      table:
        uid: onu1tqo14vr
        type: table
        grid_uid: ''
        fields:
          name:
            wrapper: 5qq6nk7lkk6
            field: benwr8k0k98
          code:
            wrapper: t4lqm7wpulk
            field: uhejd322eq8
          email:
            wrapper: 5itftu4vsm6
            field: yvqw6nlo981
          phone:
            wrapper: 71r8wwest9e
            field: 6l3wccds5hf
          rating:
            wrapper: okydv71wpdx
            field: jl3fk0ejaz3
          status:
            wrapper: h52i87l9647
            field: i93zhibk7jp
          contactPerson:
            wrapper: x3yhx1x9qax
            field: dsmpyd2tjsm
        actions:
          filter:
            uid: k355j4bokl6
          refresh:
            uid: polozc92s49
          addNew:
            uid: n2ohvibhp1c
          export:
            uid: e0l0bkaelhf
        record_actions:
          edit:
            uid: o57zaio8l1n
          delete:
            uid: xlr5ajrhxbb
  warehouses:
    route_id: 358340360404994
    page_uid: 6syd5hxopv4
    tab_uid: n68aiv92rzr
    grid_uid: 3k6cblavhpo
    blocks:
      filterForm:
        uid: 4gu8b8r42m7
        type: filterForm
        grid_uid: 5omtlbccjij
        fields:
          location:
            wrapper: wwcl9xy1i6h
            field: 2cfwjkp07qn
          status:
            wrapper: rgql5dorkza
            field: 3rproxd5o8u
          name:
            wrapper: h3xlihnpcbp
            field: xn8pc85fiws
      table:
        uid: 35dh6ebwqkf
        type: table
        grid_uid: ''
        fields:
          manager:
            wrapper: 7cgaqi8j2vg
            field: 4h9tib30hwd
          name:
            wrapper: xbdy4iu3wdi
            field: o2inqagbs0v
          location:
            wrapper: 1co21sgezh6
            field: wxxole0g5lb
          code:
            wrapper: gk5zbke52om
            field: wxydga9qv4a
          capacity:
            wrapper: 96qsfkofhc2
            field: x1gacmwblvl
          status:
            wrapper: kmqgfv2kv0v
            field: 0rsio677ri3
        actions:
          filter:
            uid: 88j514so4wi
          refresh:
            uid: olu8tqmuhlf
          addNew:
            uid: 4zg2b98dlza
          export:
            uid: 8fivj6pn7sx
        record_actions:
          edit:
            uid: zcknvyc8fq2
          delete:
            uid: kinc65ufdx2
  stock_movements:
    route_id: 358340362502144
    page_uid: ij5kugpdi2p
    tab_uid: mitcj4y2smk
    grid_uid: 53p3o56pfzo
    blocks:
      filterForm:
        uid: nl255qsveah
        type: filterForm
        grid_uid: e6pif1pq2q1
        fields:
          referenceNo:
            wrapper: 4m1hvfnjqhe
            field: lcehi39kzp6
          movementDate:
            wrapper: 2lby6knrk2z
            field: v20cgqh7wjf
          movementType:
            wrapper: uxt6nwjc38o
            field: he0hg7zwo9h
      table:
        uid: bidjbhrczq0
        type: table
        grid_uid: ''
        fields:
          referenceNo:
            wrapper: 05kx6wf0vqe
            field: 3umnpjdvojg
          warehouse:
            wrapper: ir70njai86o
            field: eg0bhw9rxy2
          quantity:
            wrapper: 9bf7n52g7gb
            field: zbc83rkec4w
          movementType:
            wrapper: 4cw8mk8reyd
            field: aluq21jkqre
          product:
            wrapper: 4dyevgrcx43
            field: un23ao15kbu
          movementDate:
            wrapper: gly9bf32ndf
            field: e4zjha4t87y
          createdBy:
            wrapper: hmfzi3ienfm
            field: qtz1q85o4lw
        actions:
          filter:
            uid: gqlcr9hg956
          refresh:
            uid: jqcebk0fl0c
          addNew:
            uid: c70zzavycd7
          export:
            uid: l0jf24epzn3
        record_actions:
          edit:
            uid: 3l30abuab4i
          delete:
            uid: zu88d67eihe
