- title: PM
  type: group
  icon: projectoutlined
  children:
    - title: Projects
      icon: fundprojectscreenoutlined
    - title: Tasks
      icon: checksquareoutlined
    - title: Members
      icon: teamoutlined
    - title: Dashboard
      icon: dashboardoutlined
    - title: Team
      icon: teamoutlined
    - title: Milestones
      icon: flagoutlined
    - title: Risks
      icon: warningoutlined
