- title: PM
  type: group
  icon: projectoutlined
  children:
    - title: Dashboard
      icon: dashboardoutlined
    - title: Projects
      icon: fundprojectscreenoutlined
    - title: Tasks
      icon: checksquareoutlined
    - title: Members
      icon: teamoutlined
