blocks:
  - key: filterForm
    type: filterForm
    coll: nb_pm_tasks
    fields:
      - field: name
        label: Search
        filterPaths:
          - name
          - description
      - status
    field_layout:
      - - name
        - status
  - key: table
    type: table
    coll: nb_pm_tasks
    fields:
      - field: name
        popup: true
      - status
      - createdAt
    actions:
      - filter
      - refresh
      - addNew
    recordActions:
      - edit
      - delete
layout:
  - - filterForm
  - - table
