- title: Main
  type: group
  icon: dashboardoutlined
  children:
    - title: Overview
      icon: calendaroutlined
    - title: Leads
      icon: useraddoutlined
    - title: Customers
      icon: teamoutlined
    - title: Opportunities
      icon: fundoutlined
    - title: Orders
      icon: shoppingcartoutlined
    - title: Products
      icon: appstoreoutlined
    - title: Analytics
      icon: areachartoutlined
    - title: More Charts
      type: group
      children:
        - title: SalesManager
          icon: useroutlined
        - title: SalesRep
          icon: solutionoutlined
        - title: Executive
          icon: crownoutlined
- title: Other
  type: group
  icon: appstoreaddoutlined
  children:
    - title: Stage Settings
      icon: apartmentoutlined
    - title: Exchange Rate
      icon: dollaroutlined
    - title: Activity
      icon: orderedlistoutlined
    - title: Emails
      icon: mailoutlined
    - title: Contacts
      icon: usergroupaddoutlined
    - title: Data Analysis
      icon: compassoutlined
- title: Lookup
  icon: monitoroutlined
- title: ERPTest
  type: group
  icon: projectoutlined
  children:
    - title: Dashboard
      icon: dashboardoutlined
    - title: Categories
      icon: appstoreoutlined
    - title: Products
      icon: shoppingoutlined
    - title: Suppliers
      icon: teamoutlined
    - title: Purchase Orders
      icon: fileoutlined
    - title: PO Items
      icon: unorderedlistoutlined
    - title: Warehouses
      icon: homeoutlined
    - title: Inventory
      icon: daboredoutlined
